// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XQy7PJMx521WXd9QBHi3lvC_IreXktU',
    appId: '1:91440791445:web:43efedd2543daa6826c09c',
    messagingSenderId: '91440791445',
    projectId: 'tomenotas',
    authDomain: 'tomenotas.firebaseapp.com',
    storageBucket: 'tomenotas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmkWpnE_y5RNJPoF1YY875BKFMTok8bnk',
    appId: '1:91440791445:android:1cfbe732616a0d3226c09c',
    messagingSenderId: '91440791445',
    projectId: 'tomenotas',
    storageBucket: 'tomenotas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9OkpdygQIAFj5F6QxKCwEKjl8bW_bFs',
    appId: '1:91440791445:ios:47a8a125378446fa26c09c',
    messagingSenderId: '91440791445',
    projectId: 'tomenotas',
    storageBucket: 'tomenotas.appspot.com',
    iosClientId: '91440791445-rko0rl1n38862g3ruqn3i1e3n2io9ib7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomeNotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9OkpdygQIAFj5F6QxKCwEKjl8bW_bFs',
    appId: '1:91440791445:ios:a38bc6a4d7ce65cc26c09c',
    messagingSenderId: '91440791445',
    projectId: 'tomenotas',
    storageBucket: 'tomenotas.appspot.com',
    iosClientId: '91440791445-30pbnqd2rre1epn3ogs21ulu6s6av1rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomeNotas.RunnerTests',
  );
}
